import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider, useCart } from "@/context/CartContext";
import Link from "next/link";
import Navbar from "@/app/components/Navbar";
import { Toaster } from "react-hot-toast";
import "@/app/lib/fontawesome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shopify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <Navbar />
          <div className="pt-20">{children}</div>
        </CartProvider>

        <Toaster
          position="top-center"
          toastOptions={{
            duration: 2000,
          }}
        />
      </body>
    </html>
  );
}
